version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cross-fetch
    versions:
    - 3.0.6
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.1.3
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: redux
    versions:
    - 4.0.5
